name: Continuous Build

on:
  workflow_dispatch: # Enable manual trigger
  push:
    branches: 'package/*'
    tags: '*'

env:
  MINGW_ROOT: 'C:\MinGW'
  MSYS2_ROOT: 'C:\msys64'

jobs:
  init:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - name: Check a build environment
        run: |
          Get-CimInstance win32_operatingsystem -Property Caption, OSArchitecture, Version | fl Caption, OSArchitecture, Version
          $PSVersionTable
          git --version
          choco --version
      - name: Detect a target package # from a tag name or a branch name
        run: |
          $refs = $env:GITHUB_REF -split '/'
          if ($refs[1] -eq 'tags') {
            $packageId = $refs[2]
          } else if (($refs[1] -eq 'heads') -and ($res[2] -eq 'package')) {
            $packageId = $refs[3]
          } else {
            $message = 'Cannot extract a package id from ref "{0}"' -f $env:GITHUB_REF
            Write-Error -Message $message
            exit 1
          }
          'Package:{0},Version:{1}' -f $env:PACKAGE_ID, $env:PACKAGE_VERSION
  package:
    runs-on: windows-2019
    steps:
      - run: echo Packaging
  publish:
    runs-on: windows-2019
    steps:
      - run: echo Publishing
